name: Tests

on: [push]

jobs:
  test-latest:
    name: Test on Latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Test
        run: make test

  test-windows-latest:
    name: Build on Latest (Windows)
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        run: cargo check

  test-stable:
    name: Build on 1.48.0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          profile: minimal
          override: true
      - name: Build
        run: cargo check
